PLAYER_PLAYER_ELASTICITY = 0.55
PLAYER_BALL_ELASTICITY = 0.85
BALL_FRICTION = 0.994
KICK_FORCE = 400.0
KICK_COOLDOWN = 0.28
KICK_BONUS_FROM_PLAYER_VEL = 1.10

TICK_RATE = 60
DT = 1.0 / TICK_RATE

SNAPSHOT_RATE = 25
SNAPSHOT_EVERY = max(1, TICK_RATE // SNAPSHOT_RATE)

MAX_PLAYERS = 6
